# Generated by Django 2.2.2 on 2019-06-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190616_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.Project', verbose_name='Related Projects'),
        ),
    ]
