# Generated by Django 2.2.4 on 2019-09-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190708_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(default='images/stock-computer.jpg'),
        ),
    ]
