# Generated by Django 2.2.4 on 2019-09-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(default='/static/images/default.jpg'),
        ),
    ]
